name: podx builds
on: push
# on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: build openresty
        run: build-openresty
          #
          # CONTAINER=$(buildah from docker.io/openresty/openresty:alpine-apk )
          # buildah run ${CONTAINER} -- sh -c 'printenv' || true
          # buildah run ${CONTAINER} openresty -V || true

          
      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

