name: podx builds
on: push
# on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build images
        run: |
          # make build-alpine
          # make build-w3m
          # make build-curl
          # make build-cmark
          make certs
          # make build-openresty
          # podman images
