name: podx builds
on:
  schedule:
    - cron: '0 2 * * 2'  #  2am every Tuesday
  push:
    branches:
    - main
    paths-ignore:
    - '**/README.md'
    - '**/.env'
    - '**/latest'
jobs:
  build:
    name: build and push images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: build images
        run: make
