name: podx builds
on:
  push:
    branches:
    - main
    paths-ignore:
    - '**/README.md'
    - '**/.env'
    - '**/latest'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: build images
        shell: bash
        run: |
          make versions
          make lua-language-server
          # # make build-w3m
          # make build-curl
          # make build-cmark
          # make certs
          # make build-openresty
          echo '----------------'
          cat .env
          echo '----------------'
          podman images
