name: podx builds
on:
  push:
    branches: pods*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: podman pull our images
        run: make pods-pull
      - name: podman create our volumes for podx
        run: make volumes
      - name: podman create the podx pod
        run: make podx
